### ISSUE TITLE
java.lang.IllegalStateException while calling kiteConnect.placeOrder()

### ISSUE THREAD

**Issue by vikas-vasani** [zerodhatech/javakiteconnect#12]
Sometimes I get below error while placing CO LIMIT order

java.lang.IllegalStateException: closed
	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:398)
	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:392)
	at okhttp3.internal.Util.bomAwareCharset(Util.java:449)
	at okhttp3.ResponseBody.string(ResponseBody.java:174)
	at com.zerodhatech.kiteconnect.kitehttp.KiteResponseHandler.handle(KiteResponseHandler.java:24)
	at com.zerodhatech.kiteconnect.kitehttp.KiteRequestHandler.postRequest(KiteRequestHandler.java:85)
	at com.zerodhatech.kiteconnect.KiteConnect.placeOrder(KiteConnect.java:282)

Please check

**Comment by kssujithcj** [comment]
We need more data on this to debug. It would be helpful if you can post the steps to reproduce.

**Comment by kssujithcj** [comment]
Closed this issue since it is inactive for a long time.
